# Generated by Django 4.2.17 on 2025-03-13 19:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoPersonaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karma', models.IntegerField(default=0, verbose_name='Karma')),
                ('dinero', models.FloatField(default=0, verbose_name='Dinero')),
                ('fama', models.IntegerField(default=0, verbose_name='Fama')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Atributos extra')),
            ],
            options={
                'verbose_name': 'Atributo de personaje',
                'verbose_name_plural': 'Atributos de personaje',
            },
        ),
        migrations.CreateModel(
            name='Mazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('version', models.CharField(max_length=20, verbose_name='Versión')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Mazo',
                'verbose_name_plural': 'Mazos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NivelDeNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_nivel', models.PositiveIntegerField(verbose_name='Número de nivel')),
                ('n_wachines_necesarios', models.PositiveIntegerField(verbose_name='Número de trabajadores necesarios')),
                ('plus_de_beneficio', models.FloatField(verbose_name='Plus de beneficio')),
            ],
            options={
                'verbose_name': 'Nivel de negocio',
                'verbose_name_plural': 'Niveles de negocio',
                'ordering': ['n_nivel'],
            },
        ),
        migrations.CreateModel(
            name='CartaPersonaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('historia', models.TextField(verbose_name='Historia')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='personajes/', verbose_name='Imagen')),
                ('atributos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cards.atributopersonaje', verbose_name='Atributos')),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas_personaje', to='cards.mazo', verbose_name='Mazo')),
            ],
            options={
                'verbose_name': 'Carta de personaje',
                'verbose_name_plural': 'Cartas de personaje',
            },
        ),
        migrations.CreateModel(
            name='CartaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('costo', models.PositiveIntegerField(verbose_name='Costo')),
                ('beneficio_base', models.FloatField(verbose_name='Beneficio base')),
                ('beneficios_por_turno', models.TextField(verbose_name='Beneficios por turno en cada nivel')),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas_negocio', to='cards.mazo', verbose_name='Mazo')),
                ('niveles_soportados', models.ManyToManyField(related_name='cartas', to='cards.niveldenegocio', verbose_name='Niveles soportados')),
            ],
            options={
                'verbose_name': 'Carta de negocio',
                'verbose_name_plural': 'Cartas de negocio',
            },
        ),
        migrations.CreateModel(
            name='CartaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('frase', models.CharField(max_length=200, verbose_name='Frase')),
                ('consigna', models.TextField(verbose_name='Consigna')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='especiales/', verbose_name='Imagen')),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas_especiales', to='cards.mazo', verbose_name='Mazo')),
            ],
            options={
                'verbose_name': 'Carta especial',
                'verbose_name_plural': 'Cartas especiales',
            },
        ),
    ]
