# Generated by Django 4.2 on 2025-03-19 07:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('version', models.CharField(max_length=20, verbose_name='Versión')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Mazo',
                'verbose_name_plural': 'Mazos',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NivelDeNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_nivel', models.PositiveIntegerField(verbose_name='Número de nivel')),
                ('n_wachines_necesarios', models.PositiveIntegerField(verbose_name='Número de trabajadores necesarios')),
                ('costo_mejora', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Costo de mejora')),
                ('plus_de_beneficio', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='Plus de beneficio')),
            ],
            options={
                'verbose_name': 'Nivel de negocio',
                'verbose_name_plural': 'Niveles de negocio',
                'ordering': ['n_nivel'],
            },
        ),
        migrations.CreateModel(
            name='TipoDeNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de negocio',
                'verbose_name_plural': 'Tipos de negocio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CartaPersonaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='Masculino de 32 años, ingeniero...', max_length=200, verbose_name='Descripción')),
                ('historia', models.TextField(default='Recien llegado a la ciudad en busca de una aventura.', verbose_name='Historia')),
                ('imagen', models.ImageField(blank=True, default='personajes/ejemplo.png', null=True, upload_to='personajes/', verbose_name='Imagen')),
                ('dinero', models.IntegerField(default=3600, validators=[django.core.validators.MinValueValidator(0, message='El dinero no puede ser negativo'), django.core.validators.MaxValueValidator(100000, message='Límite máximo: $100.000')], verbose_name='Dinero')),
                ('karma', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0, message='El karma no puede ser negativo'), django.core.validators.MaxValueValidator(1000, message='Límite máximo: 1000')], verbose_name='Karma')),
                ('fama', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0, message='La fama no puede ser negativa'), django.core.validators.MaxValueValidator(1000, message='Límite máximo: 1000')], verbose_name='Fama')),
                ('consigna_juego', models.JSONField(blank=True, default=list, null=True, validators=[django.core.validators.MaxLengthValidator(5)], verbose_name='Consigna del personaje')),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas_personaje', to='cards.mazo', verbose_name='Mazo')),
            ],
            options={
                'verbose_name': 'Carta de personaje',
                'verbose_name_plural': 'Cartas de personaje',
            },
        ),
        migrations.CreateModel(
            name='CartaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('frase', models.CharField(blank=True, max_length=200, verbose_name='Frase')),
                ('precio', models.PositiveIntegerField(default=3600, validators=[django.core.validators.MinValueValidator(1, message='El precio no puede ser negativo'), django.core.validators.MaxValueValidator(100, message='Límite máximo: $ 100')], verbose_name='Precio del Negocio')),
                ('beneficio_base', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, message='Beneficio base minimo 1'), django.core.validators.MaxValueValidator(10, message='Beneficio base limite 10')], verbose_name='beneficio base')),
                ('beneficio_final', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, message='Beneficio final minimo 1'), django.core.validators.MaxValueValidator(10, message='Beneficio final limite 10')], verbose_name='beneficio final')),
                ('consignas_juego', models.JSONField(blank=True, default=list, null=True, validators=[django.core.validators.MaxLengthValidator(5)], verbose_name='Consignas del Negocio')),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas_negocio', to='cards.mazo', verbose_name='Mazo')),
                ('niveles_soportados', models.ManyToManyField(related_name='cartas', to='cards.niveldenegocio', verbose_name='Niveles soportados')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas_negocio', to='cards.tipodenegocio', verbose_name='Tipo de Negocio')),
            ],
            options={
                'verbose_name': 'Carta de negocio',
                'verbose_name_plural': 'Cartas de negocio',
            },
        ),
        migrations.CreateModel(
            name='CartaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('frase', models.CharField(max_length=200, verbose_name='Frase')),
                ('consignas_juego', models.JSONField(blank=True, default=list, null=True, validators=[django.core.validators.MaxLengthValidator(5)], verbose_name='Consignas de Carta Especial')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='especiales/', verbose_name='Imagen')),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas_especiales', to='cards.mazo', verbose_name='Mazo')),
            ],
            options={
                'verbose_name': 'Carta especial',
                'verbose_name_plural': 'Cartas especiales',
            },
        ),
    ]
