# Generated by Django 4.2.17 on 2025-03-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de negocio',
                'verbose_name_plural': 'Tipos de negocio',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='atributopersonaje',
            name='extra',
            field=models.TextField(blank=True, default='Recive $100 en cada turno', null=True, verbose_name='Atributos extra'),
        ),
        migrations.AlterField(
            model_name='cartanegocio',
            name='beneficios_por_turno',
            field=models.TextField(default='Produce (4 * (nivel de negocio)) wachines por turno.', verbose_name='Beneficios por turno en cada nivel'),
        ),
        migrations.AlterField(
            model_name='cartapersonaje',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='cartanegocio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.tipodenegocio', verbose_name='Tipo'),
        ),
    ]
