# Generated by Django 4.2 on 2025-03-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartapersonaje',
            old_name='consigna_juego',
            new_name='consignas_juego',
        ),
    ]
