# Generated by Django 4.2 on 2025-03-22 05:46

import cards.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_consigna_to_consignas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('code', models.CharField(default=cards.models.generate_room_code, max_length=6, primary_key=True, serialize=False, verbose_name='Código de sala')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la sala')),
                ('status', models.CharField(choices=[('created', 'Creada'), ('waiting', 'Esperando jugadores'), ('in_progress', 'En progreso'), ('finished', 'Finalizada')], default='created', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('max_participants', models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='Máximo de participantes')),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='cards.mazo', verbose_name='Mazo')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('dinero', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='El dinero no puede ser negativo'), django.core.validators.MaxValueValidator(100000, message='Límite máximo: $100.000')], verbose_name='Dinero')),
                ('karma', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='El karma no puede ser negativo'), django.core.validators.MaxValueValidator(1000, message='Límite máximo: 1000')], verbose_name='Karma')),
                ('fama', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='La fama no puede ser negativa'), django.core.validators.MaxValueValidator(1000, message='Límite máximo: 1000')], verbose_name='Fama')),
                ('userAgent', models.JSONField(blank=True, default=dict, null=True, verbose_name='Datos adicionales')),
                ('fecha_ingreso', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de ingreso')),
                ('carta_personaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='cards.cartapersonaje', verbose_name='Carta de personaje')),
                ('cartas_especiales', models.ManyToManyField(default=[], related_name='participants', to='cards.cartaespecial', verbose_name='Carta especial')),
                ('cartas_negocios', models.ManyToManyField(default=[], related_name='participants', to='cards.cartanegocio', verbose_name='Cartas de negocio')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='cards.room', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['fecha_ingreso'],
                'unique_together': {('name', 'room')},
            },
        ),
    ]
