# Generated by Django 4.2 on 2025-03-24 00:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_room_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso'),
        ),
    ]
