# Generated by Django 4.2 on 2025-03-24 06:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_participant_fecha_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('consignas_juego', models.TextField(blank=True, default='Conquista todas las panaderias.', null=True, validators=[django.core.validators.MaxLengthValidator(5)], verbose_name='Consignas de Carta Especial')),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas_objetivos', to='cards.mazo', verbose_name='Mazo')),
            ],
            options={
                'verbose_name': 'Carta de objetivo',
                'verbose_name_plural': 'Cartas de objetivo',
            },
        ),
        migrations.CreateModel(
            name='CartaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('frase', models.CharField(max_length=200, verbose_name='Frase')),
                ('consignas_juego', models.JSONField(blank=True, default=list, null=True, validators=[django.core.validators.MaxLengthValidator(5)], verbose_name='Consignas de Carta Especial')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagen')),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas_eventos', to='cards.mazo', verbose_name='Mazo')),
            ],
            options={
                'verbose_name': 'Carta de evento',
                'verbose_name_plural': 'Cartas de evento',
            },
        ),
    ]
