# Generated by Django 4.2 on 2025-03-27 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_cartaobjetivo_cartaevento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mazo',
            new_name='Version',
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Versión', 'verbose_name_plural': 'Versiones'},
        ),
        migrations.RemoveField(
            model_name='cartaespecial',
            name='mazo',
        ),
        migrations.RemoveField(
            model_name='cartaevento',
            name='mazo',
        ),
        migrations.RemoveField(
            model_name='cartanegocio',
            name='mazo',
        ),
        migrations.RemoveField(
            model_name='cartaobjetivo',
            name='mazo',
        ),
        migrations.RemoveField(
            model_name='cartapersonaje',
            name='mazo',
        ),
        migrations.RemoveField(
            model_name='room',
            name='mazo',
        ),
        migrations.AddField(
            model_name='cartaespecial',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartas_especiales', to='cards.version', verbose_name='Versión'),
        ),
        migrations.AddField(
            model_name='cartaevento',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartas_eventos', to='cards.version', verbose_name='Versión'),
        ),
        migrations.AddField(
            model_name='cartanegocio',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartas_negocio', to='cards.version', verbose_name='Versión'),
        ),
        migrations.AddField(
            model_name='cartaobjetivo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='objetivos/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='cartaobjetivo',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartas_objetivos', to='cards.version', verbose_name='Versión'),
        ),
        migrations.AddField(
            model_name='cartapersonaje',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartas_personaje', to='cards.version', verbose_name='Versión'),
        ),
        migrations.AddField(
            model_name='room',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='cards.version', verbose_name='Versión'),
        ),
    ]
