# Generated by Django 4.2 on 2025-03-27 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_rename_mazo_to_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaespecial',
            name='version',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='cartas_especiales', to='cards.version', verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='cartaevento',
            name='version',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='cartas_eventos', to='cards.version', verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='cartanegocio',
            name='version',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='cartas_negocio', to='cards.version', verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='cartaobjetivo',
            name='version',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='cartas_objetivos', to='cards.version', verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='cartapersonaje',
            name='version',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='cartas_personaje', to='cards.version', verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='room',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='cards.version', verbose_name='Versión'),
        ),
    ]
