# Generated by Django 4.2 on 2025-03-27 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_cartaespecial_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='cards.version', verbose_name='Versión'),
        ),
    ]
