# Generated by Django 4.2 on 2025-03-27 03:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_room_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='business_industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=20, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Rubro de negocio',
                'verbose_name_plural': 'Rubros de negocio',
                'ordering': ['industry_name'],
            },
        ),
        migrations.CreateModel(
            name='business_upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_name', models.CharField(max_length=30, verbose_name='Nombre de mejora')),
                ('n_wachines_necesarios', models.PositiveIntegerField(verbose_name='Número de trabajadores necesarios')),
                ('costo_mejora', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)], verbose_name='Costo de mejora')),
                ('version', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='business_upgrades', to='cards.version', verbose_name='Versión')),
            ],
            options={
                'verbose_name': 'Mejora de negocio',
                'verbose_name_plural': 'Mejoras de negocio',
                'ordering': ['upgrade_name'],
            },
        ),
        migrations.RemoveField(
            model_name='cartanegocio',
            name='beneficio_final',
        ),
        migrations.RemoveField(
            model_name='cartanegocio',
            name='niveles_soportados',
        ),
        migrations.RemoveField(
            model_name='cartanegocio',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cartanegocio',
            name='beneficio_mejorado',
            field=models.IntegerField(default=250, validators=[django.core.validators.MinValueValidator(100, message='Beneficio final minimo 100'), django.core.validators.MaxValueValidator(100000, message='Beneficio final limite 100000')], verbose_name='beneficio final'),
        ),
        migrations.AddField(
            model_name='cartanegocio',
            name='business_class_name',
            field=models.CharField(choices=[('Bronze', 'Bronce'), ('Silver', 'Plata'), ('Gold', 'Oro'), ('Platinum', 'Platino')], default='Bronze', max_length=20, verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='cartanegocio',
            name='beneficio_base',
            field=models.IntegerField(default=180, validators=[django.core.validators.MinValueValidator(100, message='Beneficio base minimo 100'), django.core.validators.MaxValueValidator(100000, message='Beneficio base limite 100000')], verbose_name='beneficio base'),
        ),
        migrations.AlterField(
            model_name='cartanegocio',
            name='precio',
            field=models.PositiveIntegerField(default=3600, validators=[django.core.validators.MinValueValidator(1000, message='El precio no puede ser negativo'), django.core.validators.MaxValueValidator(1000000, message='Límite máximo: $ 1000000')], verbose_name='Precio del Negocio'),
        ),
        migrations.DeleteModel(
            name='NivelDeNegocio',
        ),
        migrations.DeleteModel(
            name='TipoDeNegocio',
        ),
        migrations.AddField(
            model_name='cartanegocio',
            name='business_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_cards', to='cards.business_industry', verbose_name='Rubro de Negocio'),
        ),
        migrations.AddField(
            model_name='cartanegocio',
            name='business_upgrade',
            field=models.ManyToManyField(related_name='business_cards', to='cards.business_upgrade', verbose_name='Mejoras disponibles'),
        ),
    ]
