services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    volumes:
      # - ./dist:/usr/src/app/deckcard-ui/dist
      - ./frontend/deckcard-ui:/usr/src/app/deckcard-ui
      - /usr/src/app/deckcard-ui/node_modules
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-server
      - traefik.http.routers.DeckCard-front-https.entrypoints=https
      - traefik.http.routers.DeckCard-front-https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.DeckCard-front-https.tls=true
      - traefik.http.routers.DeckCard-front-https.tls.certresolver=le
      - traefik.http.routers.DeckCard-front-https.service=front-DeckCard-service
      - traefik.http.routers.DeckCard-front-https.middlewares=security-headers,admin-auth
      - traefik.http.services.front-DeckCard-service.loadbalancer.server.port=3300
    networks:
      - traefik-server
      - DeckCard-network
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # Entorno Python
      target: ${PYTHON_ENV:-development}
    volumes:
      - ./backend/API:/usr/src/app
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_HOST=${POSTGRES_DB_HOST}
      - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}

      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-server
      - traefik.http.routers.DeckCard-back-https.entrypoints=https
      - traefik.http.routers.DeckCard-back-https.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.DeckCard-back-https.tls=true
      - traefik.http.routers.DeckCard-back-https.tls.certresolver=le
      - traefik.http.routers.DeckCard-back-https.service=backend-DeckCard-service
      - traefik.http.routers.DeckCard-back-https.middlewares=security-headers
      - traefik.http.services.backend-DeckCard-service.loadbalancer.server.port=8800
    networks:
      - traefik-server
      - DeckCard-network
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_HOST: ${POSTGRES_DB_HOST}
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-server
      - traefik.http.routers.DeckCard-bd-https.entrypoints=https
      - traefik.http.routers.DeckCard-bd-https.rule=Host(`bd.${DOMAIN}`)
      - traefik.http.routers.DeckCard-bd-https.tls=true
      - traefik.http.routers.DeckCard-bd-https.tls.certresolver=le
      - traefik.http.routers.DeckCard-bd-https.service=bd-DeckCard-service
      - traefik.http.services.bd-DeckCard-service.loadbalancer.server.port=7700
    networks:
      - traefik-server
      - DeckCard-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  traefik-server:
    name: traefik-server
    external: true
  DeckCard-network:
    name: DeckCard-network
    driver: bridge
    internal: true

volumes:
  postgres_data:
