services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development} # Selecciona la etapa según el entorno
    volumes:
      - ./dist:/usr/src/app/UI/dist
      - ./frontend/UI:/usr/src/app/UI
      - /usr/src/app/UI/node_modules
    command: sh -c '[ "$NODE_ENV" = "production" ] && nginx -g "daemon off;" || npm run dev'
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-server
      # https
      - traefik.http.routers.DeckCard-front-https.entrypoints=https
      - traefik.http.routers.DeckCard-front-https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.DeckCard-front-https.tls=true
      - traefik.http.routers.DeckCard-front-https.tls.certresolver=le
      - traefik.http.routers.DeckCard-front-https.service=front-DeckCard-service
      - traefik.http.routers.DeckCard-front-https.middlewares=security-headers,admin-auth
      - traefik.http.services.front-DeckCard-service.loadbalancer.server.port=3300
    networks:
      - traefik-server
      - DeckCard-network
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${PYTHON_ENV:-development}
    volumes:
      - ./backend/API:/usr/src/app
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-1}
    command: sh -c "python manage.py runserver 0.0.0.0:8800"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-server
      - traefik.http.routers.DeckCard-back-https.entrypoints=https
      - traefik.http.routers.DeckCard-back-https.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.DeckCard-back-https.tls=true
      - traefik.http.routers.DeckCard-back-https.tls.certresolver=le
      - traefik.http.routers.DeckCard-back-https.service=backend-DeckCard-service
      - traefik.http.routers.DeckCard-back-https.middlewares=security-headers,admin-auth
      - traefik.http.services.backend-DeckCard-service.loadbalancer.server.port=8800
    networks:
      - traefik-server
      - DeckCard-network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-server
      - traefik.http.routers.DeckCard-bd-https.entrypoints=https
      - traefik.http.routers.DeckCard-bd-https.rule=Host(`bd.${DOMAIN}`)
      - traefik.http.routers.DeckCard-bd-https.tls=true
      - traefik.http.routers.DeckCard-bd-https.tls.certresolver=le
      - traefik.http.routers.DeckCard-bd-https.service=bd-DeckCard-service
      - traefik.http.services.bd-DeckCard-service.loadbalancer.server.port=7700
    networks:
      - traefik-server
      - DeckCard-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  traefik-server:
    external: true
  DeckCard-network:
    driver: bridge
    internal: true

volumes:
  postgres_data:
